### ISSUE TITLE
there is no way to catch the error in Composable

### ISSUE THREAD

**Issue by IvanKopylov** [alexzhirkevich/qrose#11]
Hi!
There was a problem that if you pass too large data to the qr code, it crashes with an error:
java.lang.IllegalArgumentException: Code length overflow (27004 > 23648). And this is the correct behavior, but there is no way to catch this error.

is it possible to add some result callback to catch the error?

**Comment by alexzhirkevich** [comment]
Exception handling is not something Compose is designed for, especially IllegalArgument one. If the QR code data is controlled by user you can either coerce input string passed to `rememberQrCodePainter` or just use the QrCodePainter class constructor and handle errors by yourself  `try { QrCodePainter(...) } `

**Comment by IvanKopylov** [comment]
@alexzhirkevich This helped, thanks!
