### ISSUE TITLE
Doesn't compile with jdk 17+

### ISSUE THREAD

**Issue by LazyHat** [alexzhirkevich/qrose#3]
it doesn't compile on jdk 17+, respectively, i can't use it on new versions of compose.
build log says:
Cannot inline bytecode built with JVM target 17 into bytecode that is being built with JVM target 1.8.

**Comment by alexzhirkevich** [comment]
It was published with jvmTarget 17 by mistake. Technically it doesn't compile on target 16-. 
You can workaround it now using
```kotlin
android {
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
```

Next version will be published with target 11.

**Comment by alexzhirkevich** [comment]
Please check `1.0.0-beta3`
