### ISSUE TITLE
Unable to build Web example

### ISSUE THREAD

**Issue by khalid64927** [alexzhirkevich/qrose#4]
I tried to clone and build webJsApp to see library in action since I'm exploring it to use it.

I encountered a couple for issues 

1. Incorrect Import on [line no 5 here ](https://github.com/alexzhirkevich/qrose/blob/main/example/webJsApp/src/jsMain/kotlin/io/github/alexzhirkevich/qrose/example/web/main.kt#L5)
2. After resolving #1 issue I got below error for copy gradle task on Android Studio HeadgHog Canary 3

`bash
qrose % ./gradlew example:webJsApp:jsBrowserDevelopmentRun

Task :example:webJsApp:jsDevelopmentExecutableCompileSync FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':example:webJsApp:jsDevelopmentExecutableCompileSync' (type 'DefaultIncrementalSyncTask').
  - Gradle detected a problem with the following location: '/Users/mohammedhamid/Documents/Projects/KMP/qrose/example/webJsApp/build/processedResources/js/main'.
    
    Reason: Task ':example:webJsApp:jsDevelopmentExecutableCompileSync' uses this output of task ':example:webJsApp:copyJsResourcesWorkaround' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':example:webJsApp:copyJsResourcesWorkaround' as an input of ':example:webJsApp:jsDevelopmentExecutableCompileSync'.
      2. Declare an explicit dependency on ':example:webJsApp:copyJsResourcesWorkaround' from ':example:webJsApp:jsDevelopmentExecutableCompileSync' using Task#dependsOn.
      3. Declare an explicit dependency on ':example:webJsApp:copyJsResourcesWorkaround' from ':example:webJsApp:jsDevelopmentExecutableCompileSync' using Task#mustRunAfter.
    
    Please refer to https://docs.gradle.org/8.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
`

**Comment by alexzhirkevich** [comment]
Thanks. Looks like broken resources configuration in web example. I'll fix it. It will work normally if you add it to your project as a gradle dependency

**Comment by khalid64927** [comment]
I can raise this PR, library looks good.

**Comment by alexzhirkevich** [comment]
Sure thing, if you want
